[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "2.0.17"
async-trait = "0.1.89"
sqlx = { version = "0.9.0-alpha.1", features = ["runtime-tokio", "postgres", "uuid"] }
tower-http = { version = "0.6.8", features = ["cors"] }
serde_json = "1.0.149"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing = "0.1.44"
tower = "0.5.2"

[dev-dependencies]
testcontainers = "0.26.3"
testcontainers-modules = { version = "0.14.0", features = ["postgres"] }

[features]
default = ["in_memory"]
in_memory = []
postgres = []
